---
- name: Push Catalog
  hosts: trino_coordinator, trino_workers
  become: yes
  vars:
    repo_local_path: "{{ project_root }}/tmp/trino-catalog"
    repo_url: 'https://github.com/sorieux/trino-admin-catalog.git'
    repo_dest_path: "/etc/trino/catalog"

  roles:
    - role: sync_repository